trigger:
  - main

pool:
  vmImage: 'macOS-latest'

stages:
    jobs:
      - job: test
        steps:
          - task: NodeTool@0
            inputs
            versionSource: 'spec'
            versionSpec: '17.5.0'
            
            - task: JavaToolInstaller@0
                inputs
                 versionSpec: '11'
                 jdkArchitectureOption: 'x64'
                 jdkSourceOption: 'PreInstalled'
            
            - script:| 
              node -v
              java -v
              npm install -g appium@next
              appium -v
              appium driver install xcuitest
              appium plugin install --source npm appium-device-farm
              
              SIMULATOR_NAME="my-sim"
              SIMULATOR_UDID=`xcrun simctl create "$SIMULATOR_NAME"
              com.apple.CoreSimulator.SimDeviceType.iPhone-12 
              com.apple.CoreSimulator.SimRuntime.iOS-14-3`
              xcrun simctl boot $SIMULATOR_UDID

pool:
  vmImage: 'macOS-latest'

  - stages: emulator
    jobs:
      - job: test
        steps:
              

            - task: Maven@3
              inputs
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: true
              effectivePomSkip: true
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: 'latest'